#' @name conditional.corPSRs
#' @aliases conditional.corPSRs
#' @title Conditional and partial-conditional correlation of probability scale residuals (PSRs)
#' @description Conditional and partial-conditional correlation of probability scale residuals (PSRs).
#' @usage conditional.corPSRs(modX, modY, z, newZ, numKnots)
#' 
#' @param modX Survival model object (see examples below) for event X generated by \code{coxph()}.
#' @param modY Survival model object (see examples below) for event Y generated by \code{coxph()}.
#' @param z The variable for which the conditional correlation is modeled.
#' @param newZ The values of variable \code{z} for which conditional correlation is computed. By default, \code{newZ = z}.
#' @param numKnots The number of knots in restricted cubic splines when modeling the conditional correlation.
#' The value can be \code{0}, \code{3}, \code{4}, \code{5}, \code{6}, or \code{7}.
#' When \code{numKnots = 0} (the default), then variable \code{z} is modeled
#' as a linear variable. When \code{numKnots > 0}, then variable \code{z}
#' is modeled using restricted cubic splines with \code{numKnots} number of knots.
#' The knots' location is chosen as suggested by Harrell [2015].
#'
#' @return The data frame with the point estimate computed for \code{newZ} values and \code{95\%} confidence intervals computed using M-estimation.
#' 
#' @details Currenly, only \code{coxph()} is implemented.
#' When fitting Cox proportional hazards model for continuous data (especially simulated data),
#' argument \code{timefix=TRUE} of \code{coxph()} needs to be set to \code{FALSE} in order
#' to avoid the 'detection' of spurious ties. The confidence intervals are computed using
#' M-estimation with the full Cox likelihood.
#' 
#' To obtain the conditional correlation of the PSRs, the covariance and 
#' variances of the probability scale residuals are modeled using linear regression. 
#' Sometimes (especially for small samples), linear regression may predict negative or zero variance.
#' When this happens, the corresponding value of the conditional correlation is NA.
#' In general, the value of the conditional correlation cannot be greater than 1 or less than -1. However,
#' the point estimates and confidence intervals are not altered to fit this restriction so the
#' user can see the magnitude of the conditional correlation variability.
#' 
#' @examples
#'    require(survival)
#'    X = c(0.5, 0.61, 0.6, 0.8, 0.78, 0.7, 0.9)
#'    Y = c(0.44, 0.15, 0.77, 0.88, 0.22, 0.99, .33)
#'    deltaX = c(1, 0, 1, 1, 0, 1, 0)
#'    deltaY = c(1, 0, 1, 0, 1, 1, 1)
#'    
#'    Z1 = c(-1.05, -0.43, -0.23, 1.19, 0.54, -0.09, -0.71)
#'    Z2 = c(-0.75, 2.03, 0.11, 1.39, 1.36, -0.71, -0.69)
#'    newZ = seq(min(Z2), max(Z2), diff(range(Z2)/10))
#'
#'    survObjX = Surv(X, deltaX)
#'    survObjY = Surv(Y, deltaY)
#'    
#'    ### conditional correlation of PSRs
#'    modX = coxph(survObjX ~ Z1, method = "breslow", timefix = FALSE)
#'    modY = coxph(survObjY ~ Z1, method = "breslow", timefix = FALSE)
#'    conditional.corPSRs(modX, modY, z = Z1, newZ = newZ, numKnots = 0)
#'
#'    ### partial-conditional correlation of PSRs
#'    modX = coxph(survObjX ~ Z1 + Z2, method = "breslow", timefix = FALSE)
#'    modY = coxph(survObjY ~ Z1 + Z2, method = "breslow", timefix = FALSE)
#'    conditional.corPSRs(modX, modY, z = Z2, newZ = newZ, numKnots = 3)
#'    
#' @references Frank E Harrell Jr. Regression modeling strategies: with applications to linear models, logistic and ordinal regression, and survival analysis. Springer, 2015.
#' @references Svetlana K Eden, Chun Li, and Bryan E Shepherd. Spearman’s rank correlation adjusting for covariates in bivariate survival data. In preparation, 2020.
#'
#' @author Svetlana K Eden, \email{svetlanaeden@gmail.com}
#'
#' @keywords probability scale residuals conditional correlation
#' @importFrom stats cor pnorm qnorm dnorm plnorm quantile model.matrix residuals
#' @export
##############################################################################################
############################################### compute conditional PSRs correlation
##############################################################################################
conditional.corPSRs = function(modX, modY, z, newZ, numKnots = 0){
  ##################################### identify the type of model
  modelX = as.character(modX$call)[1]
  modelY = as.character(modY$call)[1]
  if(modelX != modelY){
    stop("Arguments 'modX' and 'modY' should have the same type of model: coxph().")
  }
  if(modelX != "coxph"){
    stop("Only 'coxph()' with full likelihood esitmating equations is currenlty implemented.")
  }
  ###### COXPH
  scoreResX = mestimation.coxph.full.likelihood(object = modX, continuous = FALSE)
  scoreResY = mestimation.coxph.full.likelihood(object = modY, continuous = FALSE)
  
  resultXY <- prodTS.new.SKE(x.resid = scoreResX$presid, y.resid = scoreResY$presid,
                             z = z, newZ = newZ, numKnots = numKnots,
                             xres2.method="model", yres2.method="model",
                             xz.dl.dtheta = t(scoreResX$dl.dtheta),
                             yz.dl.dtheta = t(scoreResY$dl.dtheta),
                             xz.d2l.dtheta.dtheta = scoreResX$d2l.dtheta.dtheta,
                             yz.d2l.dtheta.dtheta = scoreResY$d2l.dtheta.dtheta,
                             dxresid.dtheta = scoreResX$dpresid.dtheta,
                             dyresid.dtheta = scoreResY$dpresid.dtheta, debugMode = FALSE)

  res = resultXY$pointEstAndCIs
  names(res) = c("est", "lower.CI", "upper.CI")
  res
  
}

